tasks:
  - before: >
      echo | ssh-keygen -t rsa -C "keyne.cleetus@revature.com" -q -N "" &&
      chmod 644 ~/.ssh/id_rsa.pub &&
      chmod 600 ~/.ssh/id_rsa &&
      ssh-keyscan github.com >> ~/.ssh/known_hosts
  - init: git remote set-url origin git@github.com:samar-programmer/samar-programmer-QuestionaireApplication.git
  - name: husky dependency
  - init: npm install husky --save-dev && npx husky install && npm pkg set scripts.prepare="husky install" && npx husky add .husky/post-commit "git log -1 --shortstat > history_log.txt"
vscode:
 extensions:
   - kyntrack.gitpod-plugin